### ISSUE TITLE
List of FDSN webservice addresses in signals/fdsnws.py

### ISSUE THREAD

**Issue by sheyala** [shakelab/shakelab#9]
Some of the URLs in the list of webservices (shakelab/signals/fdsnws.py, lines 29-56) are not correct. Here is the list of the working ones (from https://www.fdsn.org/datacenters/ , as reported inside each institution page):

DATA_CENTER_REGISTRY = {
    'AUSPASS' : ' http://auspass.edu.au:8080',
    'BGR' : 'https://eida.bgr.de',
    'EMSC' : 'https://www.seismicportal.eu',
    'ETH' : 'https://eida.ethz.ch',
    'GEOFON' : 'https://geofon.gfz-potsdam.de',
    'ICGC' : 'https://ws.icgc.cat',
    'IESDMC' : 'http://batsws.earth.sinica.edu.tw',
    'INGV' : 'https://webservices.ingv.it',
    'IPGP' : 'http://ws.ipgp.fr',
    'IRISDMC' : 'https://service.iris.edu',
    'ISC' : 'http://www.isc.ac.uk',
    'KAGSR' : 'http://sdis.emsd.ru',
    'KOERI' : 'https://eida.koeri.boun.edu.tr',
    'LMU' : 'https://erde.geophysik.uni-muenchen.de',
    'NCEDC' : 'http://service.ncedc.org',
    'NIEP' : 'https://eida-sc3.infp.ro',
    'NOA' : 'http://eida.gein.noa.gr',
    'ORFEUS' : 'https://orfeus-eu.org',
    'RASPISHAKE' : 'https://fdsnws.raspberryshakedata.com',
    'RESIF' : 'https://ws.resif.fr',
    'SCEDC' : 'https://service.scedc.caltech.edu',
    'UIB-NORSAR' : 'http://eida.geo.uib.no',
    'USGS' : 'https://earthquake.usgs.gov',
    'USP' : 'http://seisrequest.iag.usp.br',
    'OGS-SCP3' : 'http://158.110.30.85:8080',
    'OGS-ANT' : 'http://158.110.30.202:5600'
}

**Comment by klunk386** [comment]
The address list has been updated. Thank you!
